# Generated by Django 3.0.4 on 2020-05-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024, verbose_name='Link')),
                ('token', models.CharField(max_length=200, unique=True, verbose_name='Short Url')),
            ],
        ),
    ]
